/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd2;

import entidades.AUTOR;
import entidades.TITULO;
import entidades.TITULOAUTOR;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.driver.OracleConnection;
import sqlj.runtime.ref.DefaultContext;

/**
 *
 * @author DanMoCa14z
 */
public class TitleAuthor extends javax.swing.JFrame {

    /**
     * Creates new form TitleAuthor
     */
    public TitleAuthor() {
        initComponents();
        loadTitleAuthor();
        fillComboAutor();
        fillComboTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jCBAutor = new javax.swing.JComboBox();
        jCBTitulo = new javax.swing.JComboBox();
        jLblAutor = new javax.swing.JLabel();
        jLbltitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtFldOrdenAutor = new javax.swing.JTextField();
        jTxtTipoRegalia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("( ͡° ͜ʖ ͡°) - Titulo Autor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jCBAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAutorActionPerformed(evt);
            }
        });

        jCBTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTituloActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Autor");

        jLabel2.setText("ID Titulo");

        jLabel3.setText("Orden Autor");

        jLabel4.setText("Tipo Regalia");

        jTxtFldOrdenAutor.setPreferredSize(new java.awt.Dimension(100, 20));

        jTxtTipoRegalia.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtTipoRegalia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtFldOrdenAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBTitulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFldOrdenAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtTipoRegalia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar Cambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        fillFields();

    }//GEN-LAST:event_jTable1MouseClicked

    private void jCBAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAutorActionPerformed
        // TODO add your handling code here:
        try {
            if (jCBAutor.getSelectedItem() instanceof AUTOR) {
                AUTOR p = (AUTOR) jCBAutor.getSelectedItem();
                jLblAutor.setText(p.getAuFname() + " " + p.getAuLname());
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jCBAutorActionPerformed

    private void jCBTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTituloActionPerformed
        // TODO add your handling code here:
        try {
            if (jCBTitulo.getSelectedItem() instanceof TITULO) {
                TITULO p = (TITULO) jCBTitulo.getSelectedItem();
                jLbltitulo.setText(p.getTitleName());
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jCBTituloActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        fillFields();
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        newTituloAutor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateTituloAutor();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        deleteTituloAutor();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void clearFiields(){
        jTxtFldOrdenAutor.setText("");
        jTxtTipoRegalia.setText("");
        jCBAutor.removeAllItems();
        fillComboAutor();
        jCBTitulo.removeAllItems();
        fillComboTitulo();
        jLbltitulo.setText("");
        jLblAutor.setText("");
    }
    
    public void fillFields(){
        TITULOAUTOR x;
        x = (TITULOAUTOR) jTable1.getValueAt(jTable1.getSelectedRow(), 2);
        AUTOR a = (AUTOR) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        TITULO t = (TITULO) jTable1.getValueAt(jTable1.getSelectedRow(), 1);

        try {
            for (int i = 0; i < jCBAutor.getItemCount(); i++) {
                if (a == null) {
                    jCBAutor.setSelectedIndex(0);
                    jLblAutor.setText("");
                    break;
                }
                if (jCBAutor.getItemAt(i) instanceof AUTOR
                        && a.getAuId().equals(((AUTOR) jCBAutor.getItemAt(i)).getAuId())) {
                    jCBAutor.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i < jCBTitulo.getItemCount(); i++) {
                if (a == null) {
                    jCBTitulo.setSelectedIndex(0);
                    jLbltitulo.setText("");
                    break;
                }
                if (jCBTitulo.getItemAt(i) instanceof TITULO
                        && t.getTitleId().equals(((TITULO) jCBTitulo.getItemAt(i)).getTitleId())) {
                    jCBTitulo.setSelectedIndex(i);
                    break;
                }
            }
            this.jTxtFldOrdenAutor.setText(((x.getAuOrd()) != null) ? x.getAuOrd() + "" : "");
            this.jTxtTipoRegalia.setText(((x.getRoyaltyper()) != null) ? x.getRoyaltyper() + "" : "");
        } catch (SQLException ex) {
            Logger.getLogger(TitleAuthor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fillComboAutor() {
        try {
             OracleConnection conn = (OracleConnection) Conexion.GetConnection();
            Statement st = conn.createStatement();
            Map map = (Map) conn.getTypeMap();
            map.put(AUTOR._SQL_NAME, AUTOR.class);

            ResultSet rs = st.executeQuery("SELECT value(a) FROM autores a ORDER BY a.au_id");
            jCBAutor.addItem("Seleccione Autor");
            while (rs.next()) {
                AUTOR p = (AUTOR) rs.getObject(1);

                jCBAutor.addItem(p);
            }
            conn.close();
        } catch (SQLException e) {
        }
    }

    public void fillComboTitulo() {
        try {
            OracleConnection conn = (OracleConnection) Conexion.GetConnection();
            Statement st = conn.createStatement();
            Map map = (Map) conn.getTypeMap();
            map.put(TITULO._SQL_NAME, TITULO.class);

            ResultSet rs = st.executeQuery("SELECT value(a) FROM titulos a");
            jCBTitulo.addItem("Seleccione Titulo");
            while (rs.next()) {
                TITULO p = (TITULO) rs.getObject(1);
                System.out.println(p.getId());
                jCBTitulo.addItem(p);
            }
            conn.close();
        } catch (SQLException e) {
            
        }
    }

    public void loadTitleAuthor() {
        try {
            OracleConnection conn = (OracleConnection) Conexion.GetConnection();
            Statement st = conn.createStatement();
            Map map = (Map) conn.getTypeMap();
            map.put(TITULOAUTOR._SQL_NAME, TITULOAUTOR.class);

            String[] columns = {
                "ID Autor", "ID Titulo", "Orden Autor", "Regalia Tipo"
            };

            DefaultTableModel tm = new DefaultTableModel(null, columns) {
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return false;
                }
            };

            ResultSet rs = st.executeQuery("SELECT value(a) FROM titulo_autor a");
            while (rs.next()) {
                TITULOAUTOR p = (TITULOAUTOR) rs.getObject(1);
                AUTOR a = null;
                try {
                    a = p.getRefAuthor().getValue();
                } catch (SQLException e) {
                    a = null;
                }
                TITULO t = null;
                try {
                    t = p.getRefTitle().getValue();
                } catch (SQLException e) {
                    t = null;
                }

                Object[] row = {
                    a, t, p, p.getRoyaltyper()
                };

                tm.addRow(row);
            }
            jTable1.setModel(tm);
        } catch (SQLException e) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleAuthor().setVisible(true);
            }
        });
    }
    
    public void newTituloAutor(){
        try {
            OracleConnection conn = Conexion.GetConnection();
            Map map = (Map) conn.getTypeMap();
            map.put(TITULOAUTOR._SQL_NAME, TITULOAUTOR.class);
            map.put(TITULO._SQL_NAME, TITULO.class);
            map.put(AUTOR._SQL_NAME, AUTOR.class);
            DefaultContext dc = new DefaultContext(conn);

            TITULOAUTOR p = new TITULOAUTOR();
            p.setConnectionContext(dc);

            p.setAuOrd(new BigDecimal(jTxtFldOrdenAutor.getText()));
            p.setRoyaltyper(new BigDecimal(jTxtTipoRegalia.getText()));
            
            AUTOR e = (AUTOR)jCBAutor.getSelectedItem();
            e.setConnectionContext(dc);
            p.setRefAuthor(e.getref());
            
            TITULO t = (TITULO)jCBTitulo.getSelectedItem();
            t.setConnectionContext(dc);
            p.setRefTitle(t.getref());
            
            p.guardar();
            loadTitleAuthor();
            clearFiields();
        } catch (SQLException e) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void updateTituloAutor(){
        try {
            OracleConnection conn = Conexion.GetConnection();
            Map map = (Map) conn.getTypeMap();
            map.put(TITULOAUTOR._SQL_NAME, TITULOAUTOR.class);
            map.put(TITULO._SQL_NAME, TITULO.class);
            map.put(AUTOR._SQL_NAME, AUTOR.class);
            DefaultContext dc = new DefaultContext(conn);

            TITULOAUTOR p = new TITULOAUTOR();
            p.setConnectionContext(dc);
            p = (TITULOAUTOR)jTable1.getValueAt(jTable1.getSelectedRow(), 2);

            p.setAuOrd(new BigDecimal(jTxtFldOrdenAutor.getText()));
            p.setRoyaltyper(new BigDecimal(jTxtTipoRegalia.getText()));
            
            AUTOR e = (AUTOR)jCBAutor.getSelectedItem();
            e.setConnectionContext(dc);
            p.setRefAuthor(e.getref());
            
            TITULO t = (TITULO)jCBTitulo.getSelectedItem();
            t.setConnectionContext(dc);
            p.setRefTitle(t.getref());
            
            p.guardar();
            loadTitleAuthor();
            clearFiields();
        } catch (SQLException e) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void deleteTituloAutor(){
        try {
            OracleConnection conn = Conexion.GetConnection();
            Map map = (Map) conn.getTypeMap();
            map.put(TITULOAUTOR._SQL_NAME, TITULOAUTOR.class);
            DefaultContext dc = new DefaultContext(conn);

            TITULOAUTOR p = new TITULOAUTOR();
            p.setConnectionContext(dc);
            p = (TITULOAUTOR)jTable1.getValueAt(jTable1.getSelectedRow(), 2);
            
            p.borrar();
            loadTitleAuthor();
            clearFiields();
        } catch (SQLException e) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jCBAutor;
    private javax.swing.JComboBox jCBTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblAutor;
    private javax.swing.JLabel jLbltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtFldOrdenAutor;
    private javax.swing.JTextField jTxtTipoRegalia;
    // End of variables declaration//GEN-END:variables
}
